# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build sofle nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["sofle_left","sofle_right"]'
      alphas: '["QWERTY"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
